server:
  port: 8088

spring:
  jpa:
    hibernate:
      ddl-auto: none
    datasource:
      url: jdbc:h2:./db/BookstoreDb;DB_CLOSE_ON_EXIT=FALSE
      username: admin
      password: admin
    show-sql: true

jwt:
  secret: 5uRf1B1Rd
  expire: 60