CREATE TABLE tb_book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    isbn VARCHAR(16) NOT NULL,
    title VARCHAR(80) NOT NULL,
    author VARCHAR(80) NOT NULL,
    price DECIMAL NOT NULL,
    published_at DATETIME NOT NULL,
    primary key (id)
)